### ISSUE TITLE
Only ships one value for metrics with multiple tags

### ISSUE THREAD

**Issue by pdf** [tgulacsi/prometheus_scollector#1]
Metrics that should deliver values for multiple tags only deliver a single tag and value, for example `os_disk_fs_percent_free` only delivers the free space for a single mount-point, rather than one for each mount-point.

**Comment by tgulacsi** [comment]
Ok, now I have a test case to reproduce this.

I think maybe the problem lies in that I don't use  XxxVec, only ConstMetric. Have to dig deeper.

**Comment by tgulacsi** [comment]
Please test 
a3b0307e599b44180fa082cb331b58b8125bf49a !

**Comment by pdf** [comment]
@tgulacsi looks good!
