### ISSUE TITLE
Broken import

### ISSUE THREAD

**Issue by qed-** [tgulacsi/prometheus_scollector#2]
The package doesn't build, it seems that the import bosun.org/opentsdb no longer exists.

**Comment by tgulacsi** [comment]
It Works For Me, even after git pull in $GOPATH/src/bosun.org/opentsdb.

$ cd $GOPATH/src/bosun.org/opentsdb
$ git remote -v
https://github.com/bosun-monitor/bosun.git

Maybe some redirections gone awry. Shall I rewrite the import path, or vendor opentsdb ? It's only needed to decode opentsdb.DataPoint.
