### ISSUE TITLE
Feature request: Put prometheus_scollector in docker hub

### ISSUE THREAD

**Issue by StianOvrevage** [tgulacsi/prometheus_scollector#3]
It would be nice to have this exporter in the Docker hub. Someone have already packaged it here: https://github.com/diyan/prom-scollector-exporter-docker , but it would be nice with an official build from you. TIA, Stian

**Comment by tgulacsi** [comment]
https://hub.docker.com/r/tgulacsi/prometheus_scollector/

?

**Comment by StianOvrevage** [comment]
Awesome! Thanks :)
